### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by superhealing** [baka-gourd/LogUnSpam#4]
Hey i was looking at your mod, seems very useful for my usercase, however under `regexpFilterWords = []` is not very well explained, i want to filter exactly with this regex expression : `\[1 (apple), 1 (golden_apple), 1 (enchanted_golden_apple), 1 (banana)\]`
simply to filter `[1 apple, 1 golden_apple, 1 enchanted_golden_apple, 1 banana]` 
using that regex expression throw us crash, how i suppose to use properly? 
Thanks.

**Comment by GBLodb** [comment]
Please provide your crash report, so we could diagnose the problem you've ran into.

**Comment by superhealing** [comment]
Sure :
[crash-2023-02-08_14.37.00-fml.txt](https://github.com/baka-gourd/LogUnSpam/files/10732482/crash-2023-02-08_14.37.00-fml.txt)
or https://pastebin.com/uXDWihZx

**Comment by GBLodb** [comment]
> Sure : [crash-2023-02-08_14.37.00-fml.txt](https://github.com/baka-gourd/LogUnSpam/files/10732482/crash-2023-02-08_14.37.00-fml.txt) or https://pastebin.com/uXDWihZx

Sorry for being rude, but seriously?

![图片](https://user-images.githubusercontent.com/59724679/218751028-12eddeff-e360-45d0-8e4e-5ffa6a891104.png)
![图片](https://user-images.githubusercontent.com/59724679/218751117-2f645d84-eb1c-4397-8443-4a3b4d0b79c8.png)
