### ISSUE TITLE
mod does not work

### ISSUE THREAD

**Issue by Dr-WeiAL** [baka-gourd/LogUnSpam#5]
Did I set it up wrong? It doesn't block the content in the log as I set it up
[latest.log](https://github.com/baka-gourd/LogUnSpam/files/11152889/latest.log)
`commonFilterWords = [unable to find valid certification path to requested target]`

**Comment by baka-gourd** [comment]
commonFilterWords = ["unable to find valid certification path to requested target"]

**Comment by Dr-WeiAL** [comment]
Uh, this issue is a bit too old for me to even remember what I thought at the time, so shut it down
